"""empty message

Revision ID: fb24e37abe5a
Revises: dc68f7f262b3
Create Date: 2021-03-07 16:03:17.267463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb24e37abe5a'
down_revision = 'dc68f7f262b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'read_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('read_status', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
